# Generated by Django 4.0.6 on 2022-07-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('hireDate', models.DateTimeField()),
                ('fireDate', models.DateTimeField()),
                ('stavka', models.IntegerField()),
                ('base', models.IntegerField()),
                ('advance', models.IntegerField()),
                ('byHours', models.BooleanField()),
            ],
        ),
    ]
