# Generated by Django 4.0.6 on 2022-07-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awoo', '0002_rename_stavka_employee_fraction_employee_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company',
            new_name='companyName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='positionName',
        ),
    ]
