# Generated by Django 4.0.6 on 2022-07-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awoo', '0004_alter_employee_firedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fireDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
